project_id = "hhwxatbibidxzduodcka"

[functions.musicbrainz-search]
verify_jwt = false

[functions.bachtrack-sync]
verify_jwt = false

[functions.generate-concert-tags]
verify_jwt = false

[functions.bandsintown-sync]
verify_jwt = false

[functions.ticketmaster-sync]
verify_jwt = false

[functions.daily-concert-sync]
verify_jwt = false