-- Insert sample concerts with proper date casting
INSERT INTO concerts (title, venue, location, concert_date, start_time, orchestra, conductor, soloists, program, ticket_url, tags, price_range, source)
VALUES
    ('Berlin Philharmonic: Beethoven Symphony Cycle', 'Berliner Philharmonie', 'Berlin, Germany', DATE '2024-09-15', TIME '20:00', 'Berlin Philharmonic', 'Kirill Petrenko', NULL, 'Beethoven: Symphony No. 9 in D minor, Op. 125', 'https://www.berliner-philharmoniker.de', ARRAY['beethoven', 'symphony', 'classical'], '€45-€150', 'user'),
    ('Vienna New Year Concert 2024', 'Musikverein', 'Vienna, Austria', DATE '2024-01-01', TIME '11:15', 'Vienna Philharmonic', 'Christian Thielemann', NULL, 'Johann Strauss II: Waltzes and Polkas', 'https://www.wienerphilharmoniker.at', ARRAY['new-year', 'strauss', 'vienna'], '€50-€300', 'user'),
    ('Carnegie Hall: Chopin Recital', 'Carnegie Hall', 'New York, NY', DATE '2024-08-20', TIME '19:30', NULL, NULL, 'Daniil Trifonov', 'Chopin: Complete Nocturnes', 'https://www.carnegiehall.org', ARRAY['chopin', 'piano', 'recital'], '$35-$125', 'user'),
    ('London Symphony: Mahler Symphony No. 2', 'Barbican Centre', 'London, UK', DATE '2024-10-05', TIME '19:30', 'London Symphony Orchestra', 'Simon Rattle', 'Christine Goerke, Alice Coote', 'Mahler: Symphony No. 2 "Resurrection"', 'https://www.barbican.org.uk', ARRAY['mahler', 'symphony', 'resurrection'], '£25-£95', 'user'),
    ('Chicago Symphony: Tchaikovsky Spectacular', 'Symphony Center', 'Chicago, IL', DATE '2024-11-12', TIME '20:00', 'Chicago Symphony Orchestra', 'Riccardo Muti', 'Hilary Hahn', 'Tchaikovsky: Violin Concerto, Symphony No. 5', 'https://www.cso.org', ARRAY['tchaikovsky', 'violin-concerto'], '$29-$150', 'user'),
    ('La Scala: La Traviata', 'Teatro alla Scala', 'Milan, Italy', DATE '2024-12-07', TIME '20:00', 'Orchestra del Teatro alla Scala', 'Riccardo Chailly', 'Anna Netrebko, Francesco Meli', 'Verdi: La Traviata', 'https://www.teatroallascala.org', ARRAY['verdi', 'opera', 'la-traviata'], '€35-€250', 'user'),
    ('Boston Symphony: Brahms Festival', 'Symphony Hall', 'Boston, MA', DATE '2024-09-28', TIME '20:00', 'Boston Symphony Orchestra', 'Andris Nelsons', 'Emanuel Ax', 'Brahms: Piano Concerto No. 2, Symphony No. 4', 'https://www.bso.org', ARRAY['brahms', 'piano-concerto'], '$35-$175', 'user'),
    ('Royal Concertgebouw: Bach Marathon', 'Concertgebouw', 'Amsterdam, Netherlands', DATE '2024-08-30', TIME '15:00', 'Royal Concertgebouw Orchestra', 'Daniele Gatti', NULL, 'Bach: Brandenburg Concertos (Complete)', 'https://www.concertgebouw.nl', ARRAY['bach', 'brandenburg', 'baroque'], '€25-€85', 'user'),
    ('Metropolitan Opera: The Magic Flute', 'Metropolitan Opera House', 'New York, NY', DATE '2024-10-15', TIME '19:30', 'Metropolitan Opera Orchestra', 'James Levine', 'Diana Damrau, Lawrence Brownlee', 'Mozart: Die Zauberflöte', 'https://www.metopera.org', ARRAY['mozart', 'opera', 'magic-flute'], '$25-$300', 'user'),
    ('Sydney Opera House: Vivaldi Gala', 'Sydney Opera House', 'Sydney, Australia', DATE '2024-09-08', TIME '19:30', 'Australian Chamber Orchestra', 'Richard Tognetti', 'Giuliano Carmignola', 'Vivaldi: The Four Seasons, Gloria', 'https://www.sydneyoperahouse.com', ARRAY['vivaldi', 'four-seasons', 'baroque'], 'AUD $45-$150', 'user')
ON CONFLICT DO NOTHING;