-- Insert more sample classical music concerts for September and October 2025, including Hong Kong events
INSERT INTO public.concerts (
  title, venue, location, concert_date, start_time, 
  orchestra, conductor, soloists, program, 
  tags, price_range, ticket_url, source
) VALUES 
  (
    'Mahler Symphony No. 2 "Resurrection"', 
    'Hong Kong Cultural Centre Concert Hall', 
    'Hong Kong', 
    '2025-09-05', 
    '20:00',
    'Hong Kong Philharmonic Orchestra',
    'Jaap van Zweden',
    'Sarah Chang, Cecilia Bartoli, Hong Kong Philharmonic Chorus',
    'Mahler: Symphony No. 2 in C minor "Resurrection"',
    ARRAY['Mahler', 'Symphony', 'Resurrection', 'Choral'],
    'HK $280 - $1200',
    'https://www.hkphil.org',
    'sample'
  ),
  (
    'Prokofiev Romeo and Juliet Suite', 
    'Hong Kong Space Museum Theatre', 
    'Hong Kong', 
    '2025-09-12', 
    '19:30',
    'City Chamber Orchestra of Hong Kong',
    'Jean-Thorel Lalliot',
    null,
    'Prokofiev: Romeo and Juliet Suite; Ravel: Boléro',
    ARRAY['Prokofiev', 'Romeo and Juliet', 'Ballet', 'Ravel'],
    'HK $180 - $680',
    'https://www.ccohk.com',
    'sample'
  ),
  (
    'Liszt Piano Concerto No. 1', 
    'Hong Kong City Hall Concert Hall', 
    'Hong Kong', 
    '2025-09-18', 
    '20:00',
    'Hong Kong Sinfonietta',
    'Yip Wing-sie',
    'Yundi Li',
    'Liszt: Piano Concerto No. 1 in E-flat major; Chopin: Piano Concerto No. 1 in E minor',
    ARRAY['Liszt', 'Piano Concerto', 'Chopin', 'Romantic'],
    'HK $250 - $950',
    'https://www.hksinfonietta.org',
    'sample'
  ),
  (
    'Bach Mass in B Minor', 
    'Metropolitan Opera House', 
    'New York, NY', 
    '2025-09-08', 
    '19:30',
    'Metropolitan Opera Orchestra',
    'James Levine',
    'Renée Fleming, Cecilia Bartoli, Plácido Domingo, Samuel Ramey',
    'Bach: Mass in B minor, BWV 232',
    ARRAY['Bach', 'Mass', 'Sacred', 'Choral'],
    '$85 - $450',
    'https://www.metopera.org',
    'sample'
  ),
  (
    'Sibelius Symphony No. 5', 
    'Concertgebouw', 
    'Amsterdam, Netherlands', 
    '2025-09-15', 
    '20:15',
    'Royal Concertgebouw Orchestra',
    'Mariss Jansons',
    'Anne-Sophie Mutter',
    'Sibelius: Violin Concerto in D minor; Symphony No. 5 in E-flat major',
    ARRAY['Sibelius', 'Symphony', 'Violin Concerto', 'Nordic'],
    '€60 - $280',
    'https://www.concertgebouw.nl',
    'sample'
  ),
  (
    'Debussy La Mer', 
    'Suntory Hall', 
    'Tokyo, Japan', 
    '2025-09-22', 
    '19:00',
    'NHK Symphony Orchestra',
    'Paavo Järvi',
    null,
    'Debussy: La Mer; Ravel: Daphnis et Chloé Suite No. 2',
    ARRAY['Debussy', 'La Mer', 'Impressionist', 'Ravel'],
    '¥4500 - ¥18000',
    'https://www.suntory.com/suntoryhall',
    'sample'
  ),
  (
    'Mendelssohn Violin Concerto', 
    'Hong Kong Academy for Performing Arts Concert Hall', 
    'Hong Kong', 
    '2025-09-28', 
    '20:00',
    'Hong Kong Philharmonic Orchestra',
    'Edo de Waart',
    'Hilary Hahn',
    'Mendelssohn: Violin Concerto in E minor; Brahms: Symphony No. 1 in C minor',
    ARRAY['Mendelssohn', 'Violin Concerto', 'Brahms', 'Romantic'],
    'HK $300 - $1100',
    'https://www.hkapa.edu',
    'sample'
  ),
  (
    'Verdi Requiem', 
    'Royal Festival Hall', 
    'London, UK', 
    '2025-10-03', 
    '19:30',
    'London Philharmonic Orchestra',
    'Antonio Pappano',
    'Angela Gheorghiu, Elīna Garanča, Roberto Alagna, Ferruccio Furlanetto',
    'Verdi: Requiem',
    ARRAY['Verdi', 'Requiem', 'Opera', 'Choral'],
    '£45 - £220',
    'https://www.southbankcentre.co.uk',
    'sample'
  ),
  (
    'Traditional Chinese Music Gala', 
    'Hong Kong Coliseum', 
    'Hong Kong', 
    '2025-10-06', 
    '20:00',
    'Hong Kong Chinese Orchestra',
    'Yan Huichang',
    'Wu Man, Min Huifen',
    'Traditional Chinese compositions featuring pipa, erhu, and full Chinese orchestra',
    ARRAY['Chinese', 'Traditional', 'Pipa', 'Erhu'],
    'HK $200 - $800',
    'https://www.hkco.org',
    'sample'
  ),
  (
    'Grieg Piano Concerto', 
    'Grieg Hall', 
    'Bergen, Norway', 
    '2025-10-10', 
    '19:30',
    'Bergen Philharmonic Orchestra',
    'Edward Gardner',
    'Leif Ove Andsnes',
    'Grieg: Piano Concerto in A minor; Peer Gynt Suite No. 1',
    ARRAY['Grieg', 'Piano Concerto', 'Norwegian', 'Peer Gynt'],
    'NOK 450 - NOK 1200',
    'https://www.harmonien.no',
    'sample'
  ),
  (
    'Puccini Opera Highlights', 
    'Hong Kong Cultural Centre Grand Theatre', 
    'Hong Kong', 
    '2025-10-15', 
    '19:30',
    'Opera Hong Kong Orchestra',
    'Daniel Oren',
    'Kristine Opolais, Jonas Kaufmann, Bryn Terfel',
    'Highlights from La Bohème, Tosca, and Turandot',
    ARRAY['Puccini', 'Opera', 'La Bohème', 'Tosca'],
    'HK $380 - $1500',
    'https://www.operahongkong.org',
    'sample'
  ),
  (
    'Saint-Saëns Carnival of the Animals', 
    'Davies Symphony Hall', 
    'San Francisco, CA', 
    '2025-10-18', 
    '20:00',
    'San Francisco Symphony',
    'Esa-Pekka Salonen',
    'Emanuel Ax, Yuja Wang',
    'Saint-Saëns: Carnival of the Animals; Ravel: Piano Concerto in G major',
    ARRAY['Saint-Saëns', 'Carnival', 'Piano', 'Ravel'],
    '$55 - $320',
    'https://www.sfsymphony.org',
    'sample'
  ),
  (
    'Shostakovich Symphony No. 5', 
    'Hong Kong Convention and Exhibition Centre', 
    'Hong Kong', 
    '2025-10-25', 
    '20:00',
    'Hong Kong Philharmonic Orchestra',
    'Yu Long',
    null,
    'Shostakovich: Symphony No. 5 in D minor; Prokofiev: Symphony No. 1 "Classical"',
    ARRAY['Shostakovich', 'Symphony', 'Soviet', 'Prokofiev'],
    'HK $260 - $980',
    'https://www.hkphil.org',
    'sample'
  ),
  (
    'Elgar Enigma Variations', 
    'Barbican Hall', 
    'London, UK', 
    '2025-10-30', 
    '19:30',
    'London Symphony Orchestra',
    'Sir Simon Rattle',
    null,
    'Elgar: Enigma Variations; Vaughan Williams: Fantasia on a Theme by Thomas Tallis',
    ARRAY['Elgar', 'Enigma', 'British', 'Vaughan Williams'],
    '£50 - $195',
    'https://www.barbican.org.uk',
    'sample'
  )