-- Insert sample classical music concerts to populate the calendar
INSERT INTO public.concerts (
  title, venue, location, concert_date, start_time, 
  orchestra, conductor, soloists, program, 
  tags, price_range, ticket_url, source
) VALUES 
  (
    'Beethoven Symphony No. 9', 
    'Carnegie Hall', 
    'New York, NY', 
    '2024-01-15', 
    '20:00',
    'New York Philharmonic',
    'Gustavo Dudamel',
    'Anna Netrebko, Joyce DiDonato, Jonas Kaufmann, René Pape',
    'Beethoven: Symphony No. 9 in D minor, Op. 125 "Choral"',
    ARRAY['Beethoven', 'Symphony', 'Choral', 'Romantic'],
    '$75 - $350',
    'https://www.carnegiehall.org',
    'sample'
  ),
  (
    'Mozart Piano Concerto Evening', 
    'Vienna State Opera', 
    'Vienna, Austria', 
    '2024-01-18', 
    '19:30',
    'Vienna Philharmonic',
    'Herbert von Karajan',
    'Martha Argerich',
    'Mozart: Piano Concerto No. 21 in C major, K. 467; Piano Concerto No. 23 in A major, K. 488',
    ARRAY['Mozart', 'Piano Concerto', 'Classical', 'Vienna'],
    '€50 - €200',
    'https://www.wiener-staatsoper.at',
    'sample'
  ),
  (
    'Bach Brandenburg Concertos', 
    'Royal Albert Hall', 
    'London, UK', 
    '2024-01-22', 
    '19:00',
    'London Symphony Orchestra',
    'Sir Colin Davis',
    null,
    'Bach: Brandenburg Concertos Nos. 1-6, BWV 1046-1051',
    ARRAY['Bach', 'Brandenburg', 'Baroque', 'Concerto'],
    '£40 - £180',
    'https://www.royalalberthall.com',
    'sample'
  ),
  (
    'Tchaikovsky Swan Lake Suite', 
    'Mariinsky Theatre', 
    'St. Petersburg, Russia', 
    '2024-01-25', 
    '19:00',
    'Mariinsky Orchestra',
    'Valery Gergiev',
    null,
    'Tchaikovsky: Swan Lake Suite, Op. 20a; The Nutcracker Suite, Op. 71a',
    ARRAY['Tchaikovsky', 'Ballet', 'Swan Lake', 'Romantic'],
    '$60 - $280',
    'https://www.mariinsky.ru',
    'sample'
  ),
  (
    'Brahms Symphony No. 4', 
    'Symphony Hall', 
    'Boston, MA', 
    '2024-01-28', 
    '20:00',
    'Boston Symphony Orchestra',
    'Andris Nelsons',
    'Hilary Hahn',
    'Brahms: Violin Concerto in D major, Op. 77; Symphony No. 4 in E minor, Op. 98',
    ARRAY['Brahms', 'Symphony', 'Violin Concerto', 'Romantic'],
    '$45 - $250',
    'https://www.bso.org',
    'sample'
  ),
  (
    'Vivaldi Four Seasons', 
    'La Scala', 
    'Milan, Italy', 
    '2024-02-02', 
    '20:30',
    'La Scala Orchestra',
    'Riccardo Chailly',
    'Janine Jansen',
    'Vivaldi: The Four Seasons; Albinoni: Adagio in G minor',
    ARRAY['Vivaldi', 'Four Seasons', 'Baroque', 'Violin'],
    '€70 - €400',
    'https://www.teatroallascala.org',
    'sample'
  ),
  (
    'Mahler Symphony No. 5', 
    'Berlin Philharmonie', 
    'Berlin, Germany', 
    '2024-02-05', 
    '20:00',
    'Berlin Philharmonic',
    'Kirill Petrenko',
    null,
    'Mahler: Symphony No. 5 in C-sharp minor',
    ARRAY['Mahler', 'Symphony', 'Late Romantic', 'Berlin'],
    '€55 - €320',
    'https://www.berliner-philharmoniker.de',
    'sample'
  ),
  (
    'Chopin Piano Recital', 
    'Musikverein', 
    'Vienna, Austria', 
    '2024-02-08', 
    '19:30',
    null,
    null,
    'Krystian Zimerman',
    'Chopin: Ballade No. 1 in G minor, Op. 23; Piano Sonata No. 2, Op. 35; Nocturnes',
    ARRAY['Chopin', 'Piano Recital', 'Romantic', 'Solo'],
    '€45 - €180',
    'https://www.musikverein.at',
    'sample'
  ),
  (
    'Dvořák New World Symphony', 
    'Chicago Symphony Hall', 
    'Chicago, IL', 
    '2024-02-12', 
    '20:00',
    'Chicago Symphony Orchestra',
    'Riccardo Muti',
    'Yo-Yo Ma',
    'Dvořák: Cello Concerto in B minor, Op. 104; Symphony No. 9 "From the New World"',
    ARRAY['Dvořák', 'New World', 'Cello Concerto', 'Romantic'],
    '$50 - $275',
    'https://www.cso.org',
    'sample'
  ),
  (
    'Rachmaninoff Piano Concerto No. 2', 
    'Sydney Opera House', 
    'Sydney, Australia', 
    '2024-02-15', 
    '19:30',
    'Sydney Symphony Orchestra',
    'David Robertson',
    'Lang Lang',
    'Rachmaninoff: Piano Concerto No. 2 in C minor, Op. 18; Tchaikovsky: Symphony No. 6 "Pathétique"',
    ARRAY['Rachmaninoff', 'Piano Concerto', 'Romantic', 'Tchaikovsky'],
    'AUD $65 - $295',
    'https://www.sydneyoperahouse.com',
    'sample'
  ),
  (
    'Mozart Requiem', 
    'Westminster Abbey', 
    'London, UK', 
    '2024-02-18', 
    '19:00',
    'Academy of St Martin in the Fields',
    'Neville Marriner',
    'Kiri Te Kanawa, Sarah Connolly, Mark Padmore, Bryn Terfel',
    'Mozart: Requiem in D minor, K. 626',
    ARRAY['Mozart', 'Requiem', 'Choral', 'Sacred'],
    '£35 - $160',
    'https://www.westminster-abbey.org',
    'sample'
  ),
  (
    'Stravinsky The Rite of Spring', 
    'Walt Disney Concert Hall', 
    'Los Angeles, CA', 
    '2024-02-22', 
    '20:00',
    'Los Angeles Philharmonic',
    'Esa-Pekka Salonen',
    null,
    'Stravinsky: The Rite of Spring; Debussy: La Mer',
    ARRAY['Stravinsky', 'Rite of Spring', 'Modern', 'Debussy'],
    '$40 - $220',
    'https://www.laphil.com',
    'sample'
  );