// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhwxatbibidxzduodcka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhod3hhdGJpYmlkeHpkdW9kY2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzcwNjAsImV4cCI6MjA2OTAxMzA2MH0.ProsQjvVxhwQMpjWWvGpFcbv9OOzGgOavjr9uOzgCZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});